[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "688d0f7a6d1c933e1a72aab1729fd6a7b7dd7910"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "11fb468221a7da7fe8aedfa7701296207362870ced59a1d0b5c9988cd3697830"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.aarch64-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "173e5e8f9a3b73e5d06f5538dc3988a556104aa3"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "911ac6d3f5340ece7bc55f06bed880d4ca44520c5d55b50dcf722853b4072559"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.i686-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "3c2876363651d66ae6b9c36c482d9160a9151c09"
os = "windows"

    [[Libtask.download]]
    sha256 = "3dd17460d7bdeb9914e0a67b6517a998f456a5fc51e07e3d584cd0ad23f5ff22"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.i686-w64-mingw32.tar.gz"
[[Libtask]]
arch = "powerpc64le"
git-tree-sha1 = "d3a51f0b7141e926d2a0e18f97ef8fb78819bd37"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "ab6bdb03193763800c3fabd108d851718b089c498e30950118cb771559c75039"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.powerpc64le-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "4e67f72ba44583d4db3b75eb16cb56fc9ffc452c"
os = "macos"

    [[Libtask.download]]
    sha256 = "9eb6c3492444103492cfcb7c6ced082c558574b5c6e57577e3a48385a14038e6"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.x86_64-apple-darwin14.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "f8d53e25f304c34ef5de937df8d969c3dfbd2980"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "c8f0a224ef342345ea1002a6726d29969b9236f4d3b1427999a56fe2e71b39fe"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.x86_64-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "9a7ca66e7ad856a4e91e94880438e3b8bc35735c"
os = "windows"

    [[Libtask.download]]
    sha256 = "fb1b060d94b955107e384c033db20c4ea23ed0265165e47e6ea5e0d68fa56093"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.2+0/Libtask.v0.3.2.x86_64-w64-mingw32.tar.gz"
