[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "b3e910e88bdeda515f4a9c2126fadd690de030cc"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "d7a6ea2ed580830ca2ee7ed1b17478aa28bfb3bd083a0f1cb11ed5d71d296cb1"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.aarch64-linux-gnu.tar.gz"
[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "b3c85cf7ac88f9bca0aacba42d9c636b14f5a773"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "4f3c3e7f90ac91cdc65a6574be60b117f3948922fcbb08d7716913a4e60da86f"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.aarch64-linux-musl.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e3a243a24b976d49f72613e0233f3423adadcde"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "2d364d69712b654edd09b5aff6aa11d8e12051b546297361b7ab655aeded372c"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03fb5c4d273adad55d1c25470e5945dd2e8ac075"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "40370f03530693ab0c21dd00343f9b467e8c2f79e921988757d04353f188013c"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "6c7dc043658074314b45c7fe32ce930c5bb7a4d1"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "e42e1f94765dec76d3dfdfb87d77e95bfbc477a4f72374595f560ceee37f276f"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.i686-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "a56edd97c63d094d8c27e42f765aa353683705bb"
os = "windows"

    [[Libtask.download]]
    sha256 = "aed218fcdcbf4d2b0f60cf7b5dd0711300c632fb50088ea30d7296b64e50eacd"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.i686-w64-mingw32.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "21736b2d3a582f199df0b5c60674afea57a98457"
os = "macos"

    [[Libtask.download]]
    sha256 = "2f39b4112e9b9614273e4dc508febfb37c30ff3e418d28522e0f28480687a481"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.x86_64-apple-darwin.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "8b382de16e915ff3dca32b02dd1382dcd62889a0"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "a7d4a833b0456fbf8472ffcec3dc9300fcee85754299c53516c58fd01fcc91bf"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.x86_64-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "b022e618c4ba11e2ee6bdff444a3926b5c01d9a1"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "246f653c807bac29fedb79b64aadc7547400f8a71088970584b94427c6afd38d"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.x86_64-linux-musl.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "60c36b3e57c1cff7dc25db50da46c33fd2237160"
os = "freebsd"

    [[Libtask.download]]
    sha256 = "2a9802914dfd89c5b53f6faaf1fff6e40f067bf0b7dc9feae8a767a1312c8c43"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "f95d29d6dc907cf8a05783e502acfe3ab033e3ca"
os = "windows"

    [[Libtask.download]]
    sha256 = "ba70663aa78e0aa1132c343dcfb82707e32d2f7e436c9b0ee381152e4d614a7a"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.0+0/Libtask.v0.5.0.x86_64-w64-mingw32.tar.gz"
