[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "775a18bc9d3e840126c1e3dee01a5a358807a5d8"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "6eb898e04f2cd6354e03f58c18bb3b5e274b0b68465abcf9578fa0e350f1c0c8"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.aarch64-linux-gnu.tar.gz"
[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "4796d0e73b84d9052a0f76c88a21d5684f563d2f"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "df80c8245f195f0104c3c09d83dc80ad74716e091e0870baa9cf1775d9506515"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.aarch64-linux-musl.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3643055d2bb829d180adb94d91405f82f8d94b4c"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "a0e10debb90c58b63f3986cd59bbbcabb9e3bed448d9972f52f4a511e5f3a338"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.armv7l-linux-gnueabihf.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "656db95e7cb076e629919df2acc9d3e4a9c535db"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "0a182ec19ab1e5981cdb64504d1790fe2b2ba83326f0968b44ce8ddcf816b349"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.armv7l-linux-musleabihf.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "b26c429f5b01c310d7b3a17850a6b8a80a4d5fc8"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "8516b00dab9eb3ea40c235b6bcd63e53424ffafe8c6574012cfeb988cb1a3fbb"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.i686-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "b0dc89fd433afa2d7050ef043c96df1b4ed14065"
os = "windows"

    [[Libtask.download]]
    sha256 = "dcaec9a25229523bb46e5a4c597add2d4f88a551b488b2fe33cb5ea4c904e167"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.i686-w64-mingw32.tar.gz"
[[Libtask]]
arch = "powerpc64le"
git-tree-sha1 = "3764812f32366d6db101854df883b25c1e190d90"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "86c13d767a34b00d624c3f6a72bc25303d160643985c5b2bb8dff01f7f5cb29f"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.powerpc64le-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "029f8db38904f04c3b8f756239f7e5a8cde8a83b"
os = "macos"

    [[Libtask.download]]
    sha256 = "9dff0aaf0d9863246fa7d66d261606e7610a5b04cea12b9c7baf448e4f731ec0"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.x86_64-apple-darwin.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "b329b94ccaa40f6aa00e1834f293469407329828"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "c6963033d1f0cce640e0e0d189f71de22ca4c79df7834bbfdf5f2e72315cd3eb"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.x86_64-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "3002f7dd2471eb07e4cd7eb75939d9424d04bb4d"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "7bf7e98ecd043d4722a8b75cc8999e9db39ef3decf1215a6919b77aed859b276"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.x86_64-linux-musl.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "6590e982113ed438cdbb42029e23c81186a6b804"
os = "freebsd"

    [[Libtask.download]]
    sha256 = "1ca47eccf79aa0dea96f852295a05a5ad28e4f93b7ddfa2126a6429e804ba3e1"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.x86_64-unknown-freebsd.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "ad85b2577dec2212db3c2e60a17f35549a6d731c"
os = "windows"

    [[Libtask.download]]
    sha256 = "a073014d473494e36b24f8ce05894d0d78a1189152fdf5b71cd81ddbe71c20b6"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.4.1+0/Libtask.v0.4.1.x86_64-w64-mingw32.tar.gz"
