[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "05dd629c4ebca6e668781fcf382fbe528b513de9"
os = "macos"

    [[Libtask.download]]
    sha256 = "93bf6be03236252eea33998c5fa4f0a8173d44b20266e8e05473a2ae957eebde"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.x86_64-apple-darwin14.tar.gz"
[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "a0945e33f74c4e3a1a2fba5dc6ad58e321cae4c8"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "ad342e90969280fcd198993947fb27a052357c278e40645574b93f13b9f49f25"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.aarch64-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "450d50b94394d72fb6f28698b1f75321af77fed7"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "a4061a2098da96cd6c49300b2895a61ce02d822c603ba85995d300149c9cec5e"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.i686-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "2c4f7884026d9a56981f9d10276502af4d97e0f1"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "349fc5fdd1d1234f1c1467fd655b9a5e18ac926e5b16db4ba7743b75a9540739"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.x86_64-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "2f49d120dfdbc790b237fa2cc36912a04a712242"
os = "windows"

    [[Libtask.download]]
    sha256 = "e38da986025dac5767da841cc3666973a303061f4b853c0821fc25de4802f674"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.i686-w64-mingw32.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "535cdaf0b363b220f78e5e741eb5d55d5aceac96"
os = "windows"

    [[Libtask.download]]
    sha256 = "837410807715caf15b931f04c968a3ca8967bd0d70df888d1ed535a1679030d0"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.3.1+0/Libtask.v0.3.1.x86_64-w64-mingw32.tar.gz"
