[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "ee3cda1f0990641b1fd4f29f8303aa751580d19b"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "036be44319f49b936e7e7394ca846d86cadc9206b52d12e60fb430ecd3a8e9ca"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.aarch64-linux-gnu.tar.gz"
[[Libtask]]
arch = "aarch64"
git-tree-sha1 = "1fbd572f2960245ed5c32231adb356558e6afa5e"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "17064211babedb150841903d4205260a4ea087044349c9ef9cefe477a25354ed"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.aarch64-linux-musl.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "112d63493cc4abc65fa6b37adcea19a4c6a31c06"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "18dded3b2e29de6e13682d6694e71c90c7f6a9bf7ac78e7092be975c4e5fb76f"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.armv7l-linux-gnueabihf.tar.gz"
[[Libtask]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e21934d1888241015a52578b5a39020477255cb"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "5e3049deb6f90d19fe4b970092a4b18c686bb6fc56073c7e3fce4542dd56153b"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.armv7l-linux-musleabihf.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "41ab838a39265f80df4861dcd4ce1573a1dcd8a4"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "c7a842b36c6298b170faa86f4330e089c193476972bb3042cef4ffc7afd1f3fa"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.i686-linux-gnu.tar.gz"
[[Libtask]]
arch = "i686"
git-tree-sha1 = "de3bcfda742cd3c4c7be194a59c0bd67d170350a"
os = "windows"

    [[Libtask.download]]
    sha256 = "1591967840fd56ad71489c017007612324b9c8c2eacc8f67cda3efc86d80518b"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.i686-w64-mingw32.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "8ff9da3aef0040fb2870b25c4843a75b81c3fda4"
os = "macos"

    [[Libtask.download]]
    sha256 = "cc58bb5ae71fb56251641be612bb5fd7cb504ab3ab645461534e87b8707b77bc"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.x86_64-apple-darwin.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "af721154bcefdbbde686ec8434abe0ff0e311cfc"
libc = "glibc"
os = "linux"

    [[Libtask.download]]
    sha256 = "e973e34f134b74c86068c29b0a4a1c91e0dfb329bb93bb3e1700bb45b1b0bcc0"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.x86_64-linux-gnu.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "4d43d297417344632e8ebfa2d2cf4f565ab62d44"
libc = "musl"
os = "linux"

    [[Libtask.download]]
    sha256 = "d14bf908a843b6e8c7bb454ed41413687f544bba0d8ae86221492c1d2d02c952"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.x86_64-linux-musl.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "94335189aad7fbd7b88ae164c3f18504772b384e"
os = "freebsd"

    [[Libtask.download]]
    sha256 = "f7e6325414cb99d9343b3e98febd0d4163b48583f164fd901fd1f283d2216dc1"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.x86_64-unknown-freebsd.tar.gz"
[[Libtask]]
arch = "x86_64"
git-tree-sha1 = "78ebb10f3c6e76aba4453793c07181930667c4e7"
os = "windows"

    [[Libtask.download]]
    sha256 = "ef7e23a2094515f3bc12b800a9f8d7825cea773d26c85da7a820889b4c8c0c6d"
    url = "https://github.com/JuliaBinaryWrappers/Libtask_jll.jl/releases/download/Libtask-v0.5.1+0/Libtask.v0.5.1.x86_64-w64-mingw32.tar.gz"
